### ISSUE TITLE
in jupyter the kernel is showing as 'Python 2' - should show C#

### ISSUE THREAD

**Issue by denfromufa** [zabirauf/icsharp#15]
![icsharp1](https://cloud.githubusercontent.com/assets/7870949/9835656/0ec10430-59bb-11e5-9345-b90d91be11b6.PNG)

**Comment by awb99** [comment]
@denfromufa how do you managed to run icsharp at all. I am still getting kernel errrors.


[C 12:00:49.682 NotebookApp] Malformed message: ['C71260293D3747E3960A9701A7838A04', '<IDS|MSG>', '', '{"msg_id":"2ea90403-114f-4aba-9943-a8eab7d06585","username":"icsharp_kernel","session":"C71260293D3747E3960A9701A7838A04","msg_type":"pyout","version":"4.0"}', '{"msg_id":"05C294B7EDA8485B8F09029F0378EC67","username":"username","session":"C71260293D3747E3960A9701A7838A04","msg_type":"execute_request","version":"5.0"}', '{}', '{"execution_count":1,"data":{"text/plain":"","text/html":""},"metadata":{}}']
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/zmqhandlers.py", line 184, in _on_zmq_reply
        msg = self._reserialize_reply(msg_list, channel=channel)
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/zmqhandlers.py", line 165, in _reserialize_reply
        msg = self.session.deserialize(msg_list)
      File "/usr/local/lib/python2.7/dist-packages/jupyter_client/session.py", line 843, in deserialize
        raise ValueError("Unsigned Message")
    ValueError: Unsigned Message

**Comment by denfromufa** [comment]
Because I'm not on Linux :) I think Jupyter developers discussed with you
this `unsigned message` in some discussion thread. Maybe on Mono you need
extra steps to get signed.

**Comment by denfromufa** [comment]
here is how it is possible to setup new kernels:

http://stackoverflow.com/questions/29118729/how-to-install-multiple-ipython-3-0-kernels-python-2-7-python-3-4-etc-wit

**Comment by denfromufa** [comment]
@awb99 @zabirauf we fixed both unsigned message error and ICSHARP kernel not displayed manually like discussed here:

https://groups.google.com/forum/m/#!topic/jupyter/A7XJUSI-OHc

There is still pending work to automate this and sign messages in ICSHARP side.

**Comment by csells** [comment]
I installed the Python 3.x version of Anaconda and the C# kernel is showing as "Python 3" for me.

**Comment by denfromufa** [comment]
@csells did you install kernelspec which allows you to switch kernel?
