### ISSUE TITLE
FileNotFoundError When trying to run.

### ISSUE THREAD

**Issue by KiransHub** [zabirauf/icsharp#36]
After installing I openned a notebook and selected csharp as the language. I saw a red button at the top saying Kernel error. I decided to click it to see what the problem was and it gave be the following error log: 

```
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "c:\python36\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\python36\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\python36\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\python36\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))
  File "c:\python36\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\python36\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\python36\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\python36\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\python36\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\python36\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\python36\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\python36\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "c:\python36\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "c:\python36\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 94, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\python36\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\python36\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "c:\python36\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\python36\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by lpoulain** [comment]
I received the same error when using the Python 3-based Anaconda. Switching to the Python 2 version got rid of this error (I have another error but that's another story)
