### ISSUE TITLE
Kernel crashes (WindowsError)

### ISSUE THREAD

**Issue by lpoulain** [zabirauf/icsharp#40]
I'm trying to get ICSharp working with the latest version of Jupyter, but the kernel keeps crashing.

After getting the same error as on [Issue 36](https://github.com/zabirauf/icsharp/issues/36), I installed Anaconda w/ Python 2.7. Now I get a different error:

```
Traceback (most recent call last):
  File "D:\Utils\anaconda2\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "D:\Utils\anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "D:\Utils\anaconda2\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "D:\Utils\anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "D:\Utils\anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "D:\Utils\anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "D:\Utils\anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "D:\Utils\anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "D:\Utils\anaconda2\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "D:\Utils\anaconda2\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 94, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "D:\Utils\anaconda2\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "D:\Utils\anaconda2\lib\site-packages\jupyter_client\manager.py", line 257, in start_kernel
    **kw)
  File "D:\Utils\anaconda2\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "D:\Utils\anaconda2\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "D:\Utils\anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\Utils\anaconda2\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Based on the source code, the error happens when Jupyter attempts to spawn a new process. It is weird because the Python 2 kernel works fine.

**Comment by zabirauf** [comment]
@lpoulain Meanwhile you can use docker to pull the image and run. That is pretty reliable and less hassle to setup.

```
> docker pull zabirauf/icsharp
> docker run -i -t -p 8888:8888 -v /tmp/notebooks:/home/condauser/notebooks zabirauf/icsharp
```

Make sure to replace `/tmp/notebooks` with the local directory where you want the notebooks to be saved.

**Comment by deepu2010** [comment]
Got the same issue, getting Kernel error and not able to proceed further
