### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by kagemartin** [zabirauf/icsharp#52]
Running on Ubuntu 16.04 I get the following kernel error when I open a C# notebook.

Kernel was installed to user:

`jupyter-kernelspec install kernel-spec --user`

with the following kernel.json:

```
{
    "argv": ["/home/userdir/stuff/icsharp/build/Release/bin/iCSharp.Kernel.exe", "{connection_file}"],
    "display_name": "C#",
    "language": "csharp"
}
```

This is the full error provided by clicking on the Kernel Error button:

```
Traceback (most recent call last):
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/anaconda/envs/ml36/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/anaconda/envs/ml36/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/anaconda/envs/ml36/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by kagemartin** [comment]
Looks like this can be fixed by enabling execute on the kernel executable.

`chmod +x /home/userdir/stuff/icsharp/build/Release/bin/iCSharp.Kernel.exe`

**Comment by HuangJunye** [comment]
I had this error after fixing the Errno 13 using chmod +x. 

`OSError: [Errno 8] Exec format error: '/Users/kirais/icsharp/Kernel/obj/Release/iCSharp.Kernel.exe'`

This problem is fixed by adding 'mono' in 'argv'. 

```
{
    "argv": [
      "mono",
      "/Users/kirais/icsharp/build/Release/bin/iCSharp.Kernel.exe",
      "{connection_file}"
    ],
    "display_name": "C#",
    "language": "csharp"
}
```
